language: python

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      python: 3.5
      compiler: clang
    - os: linux
      python: 3.5
      compiler: gcc
    - os: linux
      python: 3.6
      compiler: clang
    - os: linux
      python: 3.6
      compiler: gcc
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
      compiler: clang
    - os: linux
      python: 3.7
      compiler: gcc
      dist: xenial
      sudo: true
    - os: linux
      python: 3.8
      compiler: gcc
      dist: xenial
      sudo: true
    - os: linux
      python: 3.8
      compiler: clang
      dist: xenial
      sudo: true
    - os: osx
      python: 3.5
      compiler: clang
    - os: osx
      python: 3.6
      compiler: clang
    - os: osx
      python: 3.7
      compiler: clang
    - os: osx
      python: 3.8
      compiler: clang

before_install:
  - pip install codecov
  - pip install pytest --upgrade
  - pip install pytest-cov
  - pip install flake8

install:
  - python setup.py install

# command to run tests
script:
  - |
    flake8 src/minhashsketch.py src/sequence.py \
    src/tests/test_minhashsketch.py src/tests/test_sequence.py
  - |
    python -m pytest --cov=mashingpumpkins --cov-report xml --cov-report term \
    src/tests/
  - codecov
