language: python

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install coverage
  - pip install pytest-cov
  - pip install .
    
# command to run tests
script:
  - coverage run -m pytest --pdb --cov=mashingpumpkins src/
  - coverage combine