language: python

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install mmh3
  - pip install pytest-cov

# command to run tests
script:
  - py.test --cov=src 

after_success:
  - bash <(curl -s https://codecov.io/bash)