language: python

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install pytest-cov
  - pip install .
    
# command to run tests
script:
  - python -m pytest --cov=mashingpumpkins.sequence --cov=mashingpumpkins --cov-report xml --cov-report term src/
  - bash <(curl -s https://codecov.io/bash)
  