language: python

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install mmh3 --use-mirrors
  - pip install pytest-cov --use-mirrors
  - pip install -q -e . --use-mirrors

# command to run tests
script:
  - python -m pytest --cov=mashingpumpkins src/

after_success:
  - bash <(curl -s https://codecov.io/bash)