language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - pip install codecov
  - pip install pytest-cov
    
install:
  - python setup.py install
    
# command to run tests
script:
  - python -m pytest --cov=mashingpumpkins.sequence --cov=mashingpumpkins --cov-report xml --cov-report term src/
  - codecov
  