name: Publish Python Package

on:
  release:
    types: [created]
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          python-version: [3.5, 3.6, 3.7, 3.8]
          os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine
    - name: Fix Windows build environment
      if: startsWith(matrix.os, 'windows')
      run: |
        cp "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\rc.exe" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"
        cp "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\rcdll.dll" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: mashingpumpkins_${{ matrix.python-version}}_${{ matrix.os }}
        path: dist/
    - name: Publish
      if: github.event_name == 'created'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
